<?php
// config.php
$allowed_pages = [
    'home',
    'about',
    'doctorregistration',
    'doctorlogin',
    'adminlogin',
    'generalmedicine',
    'cardiology',
    'dentistry',
    'dermatology',
    'ent',
    'endocrinology',
    'nephrology',
    'neurology',
    'gastroenterology',
    'ophthalmology',
    'gynaecology',
    'paediatrics',
    'clinical',
    'bloodbank',
    'pharma',
    'emergency',
    'labservices',
    'support',
    'help',
    'patientregistration',
    // Additional pages
    'aboutus',
    'cardialogy',
    'cpyryts',
    'disadd',
    'approve',
    'connection',
    'feedback',
    'faqs',
    'developers',
    'listdoctor',
    'logout',
    'sitemap',
    'clinical',
    'gynaecology',
    'patappcancel',
    'patappdoc',
    'patappointtime',
    'patapp',
    'patappview',
    'patdetails',
    'patdocmsg',
    'patedit',
    'patienthome',
    'patientlogin',
    'patientregistration',
    'patlogout',
    'patpay',
    // Admin pages
    'admin/appview',
    'admin/details',
    'admin/docview',
    'admin/edit',
    'admin/feedbackview',
    'admin/home',
    'admin/registration',
    'admin/reportview',
    // Doctor pages
    'doctor/advice',
    'doctor/appointment',
    'doctor/details',
    'doctor/logout',
    'doctor/pat_details',
    'doctor/edit',
    'doctor/home',
];


